version: '3.9'
services:
    mysql:
        image: mysql:8
        restart: always
        ports:
            - 3306:3306
        expose:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: mysql
        volumes:
            - ${PWD}/data/mysql:/var/lib/mysql
