version: '3.9'
services:
    postgres:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        expose:
            - 5432
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - ${PWD}/data/postgresql:/var/lib/postgresql/data